#!/usr/bin/env ruby

# The MIT License (MIT)
#
# Copyright (c) 2013 William Denton
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Settings
sparkurl = "http://www.yorku.ca/spark/"

# On to business

require 'nokogiri'
require 'find'

# Cut trailing / if it's there; it will get added on later
sparkurl.chop! if sparkurl[-1] == "/"

subdirectories = []

files = Dir.glob("*")

puts %Q(<ul>)
files.each do |f|
  if File.directory?f
    subdirectories << f
  end
  if File.fnmatch("*.html", f)
    html_doc = Nokogiri::HTML(File.open(f))
    title = html_doc.xpath("/html/head/title").text
    puts %Q{<li> <a href="#{sparkurl}/#{f}">#{title}</a> </li>}
  end
end
puts %Q(</ul)

subdirectories.sort.each do |subdir|
  next if File.fnmatch("images", subdir)
  index_title = ""
  begin
    index_doc = Nokogiri::HTML(File.open("#{subdir}/index.html"))
    index_title = index_doc.xpath("/html/head/title").text
  rescue Exception => e
    index_title = "#{subdir} (no index.html)"
  end
  puts %Q{<h2><a href="#{sparkurl}/#{subdir}/">#{index_title}</h2>}
  puts "<ul>"
  Dir.glob("#{subdir}/*html").sort.each do |html|
    next if File.fnmatch("*popups*", html)
    next if File.fnmatch("*/index.html", html)
    html_doc = Nokogiri::HTML(File.open(html))
    title = html_doc.xpath("/html/head/title").text
    # puts html_doc
    puts %Q{<li> <a href="#{sparkurl}/#{html}">#{title}</a> </li>}
  end
  puts "</ul>"
end

