#!/usr/bin/env ruby

# The MIT License (MIT)
#
# Copyright (c) 2013 William Denton
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Settings

sparkurl = "http://www.library.yorku.ca/sparkdev/" # Must end in /
changefreq = "monthly" # Good enough, site isn't updated much
priority = "0.5" # Default; protocol sets it to 0.5 if undefined

# XML sitemap docs are at http://www.sitemaps.org/protocol.html

require 'nokogiri'
require 'find'

sitemap = Nokogiri::XML '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" />' 

sitemap.encoding = "UTF-8"

Find.find('.').each do |f| 
  # Skip everything not ending in .html. All these web pages do.
  next unless /html$/.match(f) 
  # And skip all the popup files, which shouldn't be seen on their own
  next if /popups/.match(f)

  # Higher priority for section index pages
  priority = "0.9" if /index.html$/.match(f)

  # Replace find's ./ with siteurl 
  loc = f.sub(/^\.\//, sparkurl) 

  # Simplify file's last modification time to YYYY-MM-DD
  lastmod = File.mtime(f).strftime("%Y-%m-%d")

  url = Nokogiri::XML::Node.new "url", sitemap
  url.add_child("<loc>#{loc}</loc>")
  url.add_child("<lastmod>#{lastmod}</lastmod>")
  url.add_child("<changefreq>#{changefreq}</changefreq>")
  url.add_child("<priority>#{priority}</priority>")
  sitemap.root.add_child(url)
end

puts sitemap.to_xml
